services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: solva-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - solva_pg_data:/var/lib/postgresql/data

  migrations-postgres:
    build: .
    container_name: solva-migrations
    depends_on:
      - postgres
    env_file:
      - .env
    command: [ "poetry", "run", "alembic", "upgrade", "head" ]

  solva-backend:
    build:
      dockerfile: ./Dockerfile
    image: solva-backend
    container_name: solva-backend
    restart: always
    ports:
      - "8085:8000"
    env_file:
      - .env

volumes:
  solva_pg_data: